---

- name: Install packages
  command: npm install -g pm2 --unsafe-perm
  notify: restart pm2
  with_items:
    - pm2
  tags:
    - web
    - pm2
    - install

- name: installing startup script
  command: >
    pm2 -s startup {{ pm2_startup }}
  tags:
    - web
    - pm2
    - install
